### ISSUE TITLE
how to get pssm data for my own pdb file and scoring of one receptor for many different ligand poses

### ISSUE THREAD

**Issue by zjujdj** [DeepRank/DeepRank-GNN-esm#7]
hello, i have two questions
(1) how to get pssm data for my own pdb file? 
(2) can deeprank-gnn-esm-predict command support scoring of one receptor for many different ligand poses, those pairs have the same esm embedding and pssm, i think. score them one by one using gpu is two slow.
thanks

**Comment by ntxxt** [comment]
Hi there, 

1) You need a local version of Blast to generate your own PSSM profile. Check this tool https://github.com/DeepRank/PSSMGen.git 
You can also check https://caps.ncbs.res.in/3pfdbplus/search.html to see if they have PSSM for your protein. 

2) Ineed score one by one is slow. If your protein has the same sequence, you only need to generate esm-2 embedding once and then after you generate your .hdf5 file, add the embedding at once to all your pbd files. this would be the fastest way. But this would require some coding yourself.

**Comment by zjujdj** [comment]
hi, thanks for you reply,
     I found that Deeprank mentioned in the article that PSSM data is not needed. Does this mean that I can also generate HDF5 data without passing the pssm_path parameter and it will still run normally? like this:
```python
from deeprank_gnn.GraphGenMP import GraphHDF5
pdb_path = "tests/data/pdb/1ATN/"
pssm_path = None
embedding_path = "tests/data/embedding/1ATN/"
nproc = 20
outfile = "1ATN_residue.hdf5"

GraphHDF5(
    pdb_path = pdb_path,
    pssm_path = pssm_path,
    embedding_path = embedding_path,
    graph_type = "residue",
    outfile = outfile,
    nproc = nproc,    #number of cores to use
    tmpdir="./tmpdir")`
```

**Comment by zjujdj** [comment]
Hello, 

```python
from deeprank_gnn.GraphGenMP import GraphHDF5
pdb_path = "tests/data/pdb/1ATN/"
pssm_path = None
embedding_path = "tests/data/embedding/1ATN/"
nproc = 20
outfile = "1ATN_residue.hdf5"

GraphHDF5(
    pdb_path = pdb_path,
    pssm_path = pssm_path,
    embedding_path = embedding_path,
    graph_type = "residue",
    outfile = outfile,
    nproc = nproc,    #number of cores to use
    tmpdir="./tmpdir")`
```
The nproc in the above code refers to the number of CPUs to use. However, when running the program, the CPU is not being utilized at all. For example, when I set nproc=4, I see in htop that the CPU utilization per process is only 25%. When I set nproc=10, each process's CPU utilization drops to only 10%. It seems that no matter how I set nproc, only one CPU is being used to execute the task, which causes the graph generation task to be very slow.

**Comment by ntxxt** [comment]
Hi there, 

1) Without pssm it will also run. 

2) Generating graph is the most time-consuming step. Multiprocessing is implemented with multiprocessing.Pool, which is a standard way of doing it.  (the code itself could be improved though) 
However, _pickle_one_graph function involves some file reading/writing, the CPU may remain idle while waiting for I/O operations to complete. This could lead to low CPU utilization despite multiprocessing. You can put the graph-gen process on a fast disk if you have one, it will help to speed things up.

**Comment by zjujdj** [comment]
Hi,
  very thanks for your timely reply!
